apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-imaisuradze
  namespace: {{ .Values.namespace }}
  labels:
{{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-imaisuradze
  template:
    metadata:
      labels:
        app: web-server-imaisuradze
{{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: index-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: index-html
          configMap:
            name: index-html