apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: imaisuradze-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: imaisuradze-role
  apiGroup: rbac.authorization.k8s.io
