apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-server-virtualservice
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.virtualService.host }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.uri }}
    route:
    - destination:
        host: web-server
        port:
          number: {{ .Values.service.port }}